import assert from 'node:assert/strict';
import fs from 'node:fs';import path from 'node:path';
import {chromium} from 'playwright';
const root=process.cwd(),checks=[],out=process.env.PORTAL_REPORT_DIR||path.join(root,'test-results');fs.mkdirSync(out,{recursive:true});
const watchdog=setTimeout(()=>{console.error('Browser check exceeded 120 seconds');process.exit(1)},120000);
const browser=await chromium.launch({headless:true,...(process.env.PORTAL_CHROME_PATH?{executablePath:process.env.PORTAL_CHROME_PATH}:fs.existsSync('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome')?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{})});
const apps=[{rowIdx:1,name:'Koo Mean Blog',url:'https://blog.koomean.com/',icon:'fab fa-github',description:'แบ่งปันเรื่องราวและเทคโนโลยี',group:'public',starred:true},{rowIdx:2,name:'Case A',url:'https://example.invalid/Docs',icon:'fas fa-star',description:'A & B',group:'public'}, {rowIdx:3,name:'Case B',url:'https://example.invalid/docs',icon:'safari',description:'คนละ URL ตัวใหญ่ตัวเล็ก',group:'public'},{rowIdx:4,name:'VeryLongApplicationNameWithoutSpaces'.repeat(6),url:'https://example.invalid/long',icon:'unknown',description:'คำอธิบายยาว'.repeat(35),group:'long'.repeat(30),starred:true},{rowIdx:5,name:'<img src=x onerror="window.__xss=1">',url:'https://example.invalid/escape',icon:'fab fa-github\" onclick=\"window.__xss=1',description:'<script>alert(1)</script>',group:'public'},{rowIdx:6,name:'Unsafe JS',url:'javascript:window.__xss=1',group:'public'},{rowIdx:7,name:'Credential URL',url:'https://name:password@example.invalid',group:'public'}];
const links=[{title:'Facebook (Wachirawich Kripindakul)',url:'https://example.invalid/social',icon:'fab fa-facebook',group:'public'},{title:'YouTube',url:'https://example.invalid/youtube',icon:'fab fa-youtube',group:'public'},{title:'Unsafe Link',url:'javascript:window.__xss=1',group:'public'}];
const user={email:'fixture@example.invalid',name:'VeryLongAccountNameWithoutSpaces'.repeat(4),role:'admin',pic:''};
const token=role=>'x.'+Buffer.from(JSON.stringify({email:user.email,exp:Math.floor(Date.now()/1000)+3600,role})).toString('base64url')+'.x';
function ok(name,value=true){assert.ok(value,name);checks.push(name);console.log('PASS '+name)}
async function setup(options={}){
 const context=await browser.newContext({viewport:{width:1440,height:960},colorScheme:'dark',reducedMotion:options.reduced?'reduce':'no-preference'});const page=await context.newPage();
 if(options.clock)await page.clock.install();
 const calls=[],errors=[],consoleErrors=[];let signedRole='admin',rateLimited=false,requiresRegistration=false,registered=false,maintenance=false,gate=null,initialToolbarY=null;
 page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error')consoleErrors.push(e.text())});
 if(options.storage)await page.addInitScript(()=>{localStorage.setItem('koomean_portal_session_v2',JSON.stringify({token:'legacy-private-token',user:{role:'admin',email:'old@example.invalid'}}))});
 if(options.blockStorage)await page.addInitScript(()=>{Storage.prototype.setItem=()=>{throw new DOMException('Unavailable')};Storage.prototype.getItem=()=>{throw new DOMException('Unavailable')};Storage.prototype.removeItem=()=>{throw new DOMException('Unavailable')}});
 await page.route('https://koomean.com/**',async r=>{const pathname=new URL(r.request().url()).pathname;const file=path.join(root,pathname==='/'?'index.html':pathname);if(!file.startsWith(root+'/')||!fs.existsSync(file))return r.fulfill({status:404,body:'missing'});return r.fulfill({path:file})});
 await page.route('https://accounts.google.com/gsi/client',async r=>{calls.push({action:'google'});if(options.googleDelay)await new Promise(resolve=>setTimeout(resolve,options.googleDelay));return r.fulfill({contentType:'application/javascript',body:`window.google={accounts:{id:{initialize:()=>{},renderButton:element=>{const b=document.createElement('button');b.textContent='Google fixture sign-in';element.appendChild(b)},disableAutoSelect:()=>{}}}}`})});
 await page.route('https://thesvg.org/**',r=>r.request().url().includes('registry')?r.fulfill({json:[{title:'GitHub',slug:'github'},{title:'Malicious',slug:'javascript:alert(1)'}]}):r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><circle cx="12" cy="12" r="10" fill="#888"/></svg>'}));
 await page.route('https://koomean-proxy.meanchannel52.workers.dev/**',async r=>{
  const params=new URLSearchParams(r.request().postData()),action=params.get('action');calls.push({action,authenticated:params.has('idToken'),params:Object.fromEntries([...params].filter(([key])=>key!=='idToken'))});
  if(action==='maintenanceStatus')return r.fulfill({json:{maintenance:{active:maintenance,note:'ทดสอบปิดปรับปรุง',reopenAt:Date.now()+60000}}});
  if(action==='bootstrap'){
   const authenticated=params.has('idToken');
   if(!authenticated && initialToolbarY===null)initialToolbarY=(await page.locator('.toolbar').boundingBox()).y;
   const data={applications:apps.filter(app=>authenticated||app.group==='public').concat(authenticated?[{rowIdx:99,name:'PrivateAdmin',url:'https://example.invalid/private',group:signedRole}]:[]),links,user:authenticated?{...user,role:signedRole}:{role:'public'},allUsers:authenticated&&signedRole==='admin'?[{...user,email:'x'.repeat(120)+'@example.invalid'}]:[]};
   if(authenticated&&requiresRegistration&&!registered)data.requireRegistration=true;
   if(gate&&authenticated){const current=gate;gate=null;current.started();await current.promise;}
   try{return await r.fulfill(rateLimited?{status:429,headers:{'Retry-After':'90'},json:{message:'Slow down'}}:{json:data})}catch{return}
  }
  if(action==='register'){registered=true;return r.fulfill({json:{success:true}})}
  if(action==='updateUserName')return r.fulfill({json:{success:true,name:params.get('newName')}});
  return r.fulfill({json:{success:true}});
 });
 await page.goto('https://koomean.com/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelector('#applications').getAttribute('aria-busy')==='false');
 return {page,context,calls,errors,consoleErrors,get initialToolbarY(){return initialToolbarY},setRole:role=>signedRole=role,setRate:v=>rateLimited=v,setRegistration:v=>requiresRegistration=v,setMaintenance:v=>maintenance=v,delayNext:()=>{let resolve,started;const promise=new Promise(r=>resolve=r);const ready=new Promise(r=>started=r);gate={promise,started};return{release:resolve,ready}},login:async(role='admin')=>{signedRole=role;await page.evaluate(token=>window.handleGoogleCredential({credential:token}),token(role));await page.waitForFunction(()=>document.querySelector('#applications').getAttribute('aria-busy')==='false');}};
}
async function within(page,selector){return page.locator(selector).evaluateAll(nodes=>nodes.filter(e=>e.offsetParent!==null).map(e=>{const r=e.getBoundingClientRect(),p=e.parentElement.getBoundingClientRect();return{selector:e.className||e.id,right:r.right,left:r.left,width:r.width,parentRight:p.right,parentLeft:p.left,scroll:e.scrollWidth,client:e.clientWidth}}).filter(r=>r.right>r.parentRight+2||r.left<r.parentLeft-2))}
async function close(page){await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('.modal-backdrop.open'))}
try{
 const env=await setup({storage:true});const {page,calls}=env;
 ok('Legacy token is removed without restoring unverified identity',await page.evaluate(()=>localStorage.getItem('koomean_portal_session_v2')===null)&&await page.locator('#admin-nav').isHidden());
 ok('Public link rail reserves layout space before the API responds',Math.abs((await page.locator('.toolbar').boundingBox()).y-env.initialToolbarY)<1);
 ok('Anonymous startup requests only bootstrap and maintenance',calls.filter(c=>!['bootstrap','maintenanceStatus'].includes(c.action)).length===0);
 ok('First render contains no blocking loader or fetched video',await page.locator('#page-loader').count()===0&&await page.locator('#hero-video').getAttribute('src')===null);
 ok('Unsafe app and marquee URLs are filtered',await page.locator('a[href^="javascript:"],a[href*="password@"],a[href*="name:"]').count()===0);
 ok('Malicious names, descriptions and icon classes stay inert',await page.evaluate(()=>!window.__xss)&&await page.locator('#applications img[onerror],#applications [onclick]').count()===0);
 await page.locator('#app-search').fill('<img');await page.waitForFunction(()=>document.querySelectorAll('.app-card').length===1);ok('Search safely highlights raw HTML-like text',await page.locator('.app-name mark').textContent()==='<img'&&await page.locator('.app-name img').count()===0);await page.locator('#app-search').fill('');await page.waitForFunction(()=>document.querySelectorAll('.app-card').length===4);
 await page.locator('[data-pin-url="https://example.invalid/Docs"]').click();ok('Favorites preserve case-sensitive URL identity and keyboard focus',await page.locator('[data-pin-url="https://example.invalid/Docs"]').getAttribute('aria-pressed')==='true'&&await page.locator('[data-pin-url="https://example.invalid/docs"]').getAttribute('aria-pressed')==='false'&&await page.evaluate(()=>document.activeElement?.dataset.pinUrl==='https://example.invalid/Docs'));
 await page.locator('#app-search').fill('no such app');await page.waitForFunction(()=>document.querySelectorAll('.app-card').length===0);ok('Empty search offers a readable state',await page.locator('.state-box').isVisible());await page.locator('#app-search').fill('');await page.waitForFunction(()=>document.querySelectorAll('.app-card').length===4);
 await page.locator('#settings-btn').click();await page.waitForTimeout(250);ok('Open dialog makes the page inert and traps keyboard focus',await page.locator('#main-content').evaluate(e=>e.inert)&&await page.locator('#settings-modal').evaluate(e=>e.contains(document.activeElement)));await page.keyboard.press('Shift+Tab');ok('Keyboard wraps inside the top dialog',await page.locator('#settings-modal').evaluate(e=>e.contains(document.activeElement)));await close(page);ok('Dialog close restores focus and hides content from accessibility tree',await page.evaluate(()=>document.activeElement.id==='settings-btn')&&await page.locator('#settings-modal').evaluate(e=>e.hidden&&e.inert&&e.getAttribute('aria-hidden')==='true'));
 await page.keyboard.press('Control+k');await page.locator('#command-search').fill('VeryLong');ok('Command palette long text stays inside its row',(await within(page,'.command-item>span:first-child')).length===0);await close(page);
 await env.login();ok('Only server verified admin response enables admin UI',await page.locator('#admin-nav').isVisible());ok('Token and account data are not persisted',await page.evaluate(()=>![...Object.values(localStorage)].some(s=>s.includes('fixture@example.invalid')||s.includes('exp'))));
 for(const width of [280,320,390,520,768,1024,1440]){
  await page.setViewportSize({width,height:900});
  for(const view of ['grid','list','compact']){
   await page.locator('#settings-btn').click();await page.locator(`#settings-modal [data-view="${view}"]`).click();await close(page);
   assert.deepEqual(await within(page,'.brand,.header-actions,.hero-title-modern,.hero-content-layer,.app-info,.app-name-row,.app-name'),[],`${width}/${view} content containment`);
   assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  }
  checks.push(`Responsive ${width}px: grid, list, compact and long account/app text fit`);
 }
 await page.setViewportSize({width:768,height:900});await page.locator('#admin-nav').click();await page.waitForTimeout(250);ok('Tablet admin columns and fields fit',(await within(page,'.admin-layout,.field,.icon-picker-row')).length===0);await page.screenshot({path:out+'/admin-tablet-after.png',animations:'disabled'});await page.locator('#users-tab-btn').click();ok('Long user email fits admin row',(await within(page,'.admin-user-info,.admin-user-controls')).length===0);await close(page);
 await page.setViewportSize({width:320,height:640});await page.locator('#auth-btn').click();await page.waitForTimeout(250);ok('Account email wraps fully within mobile dialog',(await within(page,'.user-detail-copy,#account-email,.inline-form,.field')).length===0);await page.screenshot({path:out+'/account-mobile-after.png',animations:'disabled'});await close(page);
 await page.locator('#admin-nav').click();await page.locator('[data-admin-action="edit"]').first().click();await page.locator('#admin-url').fill('javascript:alert(1)');const writesBefore=calls.length;await page.locator('#admin-submit-btn').click();ok('Admin invalid URL validation prevents writes',calls.length===writesBefore&&await page.locator('#toast-message').textContent()!=='');await page.locator('#choose-logo-btn').click();await page.waitForSelector('.logo-result');ok('Nested logo picker isolates focus and filters invalid SVG slugs',await page.locator('#admin-modal').evaluate(e=>e.inert)&&await page.locator('.logo-result img[src=""]').count()===1);await page.keyboard.press('Escape');ok('Closing nested dialog restores the parent dialog',await page.locator('#admin-modal').evaluate(e=>!e.inert&&!e.hidden));await close(page);
 await page.locator('#admin-nav').click();await page.locator('#users-tab-btn').click();env.setRole('public');await page.locator('[data-save-user]').first().click();await page.waitForFunction(()=>document.querySelector('#admin-modal').hidden);ok('Losing admin role closes management UI and clears private admin DOM',await page.locator('#admin-users').textContent()===''&&await page.locator('#admin-nav').isHidden());await env.login();
 await page.setViewportSize({width:1440,height:960});await page.locator('#settings-btn').click();await page.locator('[data-theme-value="light"]').click();await close(page);await page.waitForTimeout(250);ok('Theme preference and selected control stay synchronized',await page.evaluate(()=>document.documentElement.dataset.theme==='light')&&await page.locator('[data-theme-value="light"]').getAttribute('aria-pressed')==='true');
 const delayed=env.delayNext();await page.locator('#refresh-btn').click();await delayed.ready;await page.locator('#auth-btn').click();await page.locator('#logout-btn').click();await page.waitForFunction(()=>document.querySelector('#applications').getAttribute('aria-busy')==='false');delayed.release();await page.waitForTimeout(150);ok('Late authenticated response cannot restore data after logout',await page.locator('#admin-nav').isHidden()&&await page.locator('#applications').getAttribute('aria-busy')==='false'&&!await page.locator('#applications').textContent().then(t=>t.includes('PrivateAdmin')));
 const countBefore=await page.locator('.app-card').count();env.setRate(true);await page.locator('#refresh-btn').click();await page.waitForFunction(()=>!document.querySelector('#refresh-btn').disabled);const rateCalls=calls.length;await page.locator('#refresh-btn').click();ok('429 preserves visible apps and honors Retry-After',await page.locator('.app-card').count()===countBefore&&calls.length===rateCalls);
 ok('No application runtime error during interactions',env.errors.length===0);
 await env.context.close();
 const registered=await setup();registered.setRegistration(true);await registered.page.evaluate(t=>handleGoogleCredential({credential:t}),token('public'));await registered.page.waitForSelector('#register-modal.open');ok('New users see registration with consent required',await registered.page.locator('#register-btn').isDisabled());await registered.page.locator('#register-terms-accepted').check();await registered.page.locator('#register-btn').click();await registered.page.waitForSelector('#register-modal',{state:'hidden'});await registered.page.waitForFunction(()=>document.querySelector('#applications').getAttribute('aria-busy')==='false');ok('Registration refreshes account and catalog automatically',await registered.page.locator('#auth-label').textContent()==='บัญชี');await registered.context.close();
 const ordinary=await setup();await ordinary.login('notadmin');ok('Substring admin role does not grant admin controls',await ordinary.page.locator('#admin-nav').isHidden());await ordinary.context.close();
 const gis=await setup();await gis.page.locator('#auth-btn').click();await gis.page.waitForSelector('#google-button button');await gis.page.keyboard.press('Escape');ok('Closing login tears down the provider frame before hiding the modal',await gis.page.locator('#google-button').evaluate(e=>e.childElementCount===0));await gis.context.close();
 const slow=await setup({googleDelay:500});await slow.page.locator('#auth-btn').click();await slow.page.waitForSelector('#login-modal.open');await slow.page.keyboard.press('Escape');await slow.page.waitForTimeout(650);ok('Closing login while Google loads does not reopen it',await slow.page.locator('#login-modal').isHidden());await slow.context.close();
 const reduced=await setup({reduced:true});ok('Reduced motion stops marquee and hero entrance',await reduced.page.locator('.marquee-track').evaluate(e=>getComputedStyle(e).animationName==='none')&&await reduced.page.locator('#hero-title').evaluate(e=>getComputedStyle(e).opacity==='1'));await reduced.context.close();
 const unavailable=await setup({blockStorage:true});await unavailable.page.locator('#settings-btn').click();await unavailable.page.locator('[data-theme-value="light"]').click();await close(unavailable.page);await unavailable.page.locator('[data-pin-url]').first().click();ok('Blocked storage does not break theme or favorites',unavailable.errors.length===0);await unavailable.context.close();
 const csp=await setup();await csp.page.evaluate(()=>{const script=document.createElement('script');script.textContent='window.__injected=1';document.body.appendChild(script);const image=document.createElement('img');image.setAttribute('onerror','window.__inlineHandler=1');image.src='data:image/png,bad';document.body.appendChild(image)});await csp.page.waitForTimeout(100);ok('Browser CSP blocks injected inline script and event handler',await csp.page.evaluate(()=>!window.__injected&&!window.__inlineHandler));await csp.context.close();
 const polling=await setup({clock:true});let start=polling.calls.filter(c=>c.action==='maintenanceStatus').length;await polling.page.clock.runFor(15000);ok('Maintenance no longer polls every 15 seconds',polling.calls.filter(c=>c.action==='maintenanceStatus').length===start);await polling.page.clock.runFor(46000);await polling.page.waitForTimeout(1);ok('Maintenance refreshes on the 60 second cadence',polling.calls.filter(c=>c.action==='maintenanceStatus').length===start+1);
 await polling.page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'))});await polling.page.clock.runFor(120000);ok('Hidden tabs stop maintenance network polling',polling.calls.filter(c=>c.action==='maintenanceStatus').length===start+1);
 polling.setMaintenance(true);await polling.page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'))});await polling.page.waitForSelector('#global-maintenance-overlay:not([hidden])');ok('Maintenance overlay uses safe text and isolates page focus',await polling.page.locator('#main-content').evaluate(e=>e.inert)&&await polling.page.locator('#global-maintenance-note').textContent()==='ทดสอบปิดปรับปรุง');await polling.page.evaluate(()=>document.getElementById('settings-btn').click());ok('Maintenance blocks delayed dialog opening',await polling.page.locator('.modal-backdrop.open').count()===0&&await polling.page.locator('#global-maintenance-overlay').evaluate(e=>e===document.activeElement));await polling.context.close();
 fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({passed:checks.length,checks},null,2)+'\n');console.log(`${checks.length} browser checks passed`);
}finally{clearTimeout(watchdog);await browser.close()}
