import assert from 'node:assert/strict';
import fs from 'node:fs';import path from 'node:path';
import {chromium} from 'playwright';
const root=process.cwd(),checks=[],runtimeErrors=[],out=process.env.PORTAL_REPORT_DIR||path.join(root,'test-results');fs.mkdirSync(out,{recursive:true});
const watchdog=setTimeout(()=>{console.error('Browser check exceeded 180 seconds');process.exit(1)},180000);
const browser=await chromium.launch({headless:true,...(process.env.PORTAL_CHROME_PATH?{executablePath:process.env.PORTAL_CHROME_PATH}:fs.existsSync('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome')?{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}:{})});
const apps=[{rowIdx:1,name:'Koo Mean Blog',url:'https://blog.koomean.com/',icon:'fab fa-github',description:'แบ่งปันเรื่องราวและเทคโนโลยี',group:'public',starred:true},{rowIdx:2,name:'Case A',url:'https://example.invalid/Docs',icon:'fas fa-star',description:'A & B',group:'public'}, {rowIdx:3,name:'Case B',url:'https://example.invalid/docs',icon:'safari',description:'คนละ URL ตัวใหญ่ตัวเล็ก',group:'public'},{rowIdx:4,name:'VeryLongApplicationNameWithoutSpaces'.repeat(6),url:'https://example.invalid/long',icon:'unknown',description:'คำอธิบายยาว'.repeat(35),group:'long'.repeat(30),starred:true},{rowIdx:5,name:'<img src=x onerror="window.__xss=1">',url:'https://example.invalid/escape',icon:'fab fa-github\" onclick=\"window.__xss=1',description:'<script>alert(1)</script>',group:'public'},{rowIdx:6,name:'Unsafe JS',url:'javascript:window.__xss=1',group:'public'},{rowIdx:7,name:'Credential URL',url:'https://name:password@example.invalid',group:'public'}];
const links=[{title:'Facebook (Wachirawich Kripindakul)',url:'https://example.invalid/social',icon:'fab fa-facebook',group:'public'},{title:'YouTube',url:'https://example.invalid/youtube',icon:'fab fa-youtube',group:'public'},{title:'Unsafe Link',url:'javascript:window.__xss=1',group:'public'}];
const user={email:'fixture@example.invalid',name:'VeryLongAccountNameWithoutSpaces'.repeat(4),role:'admin',pic:''};
const token=role=>'x.'+Buffer.from(JSON.stringify({email:user.email,exp:Math.floor(Date.now()/1000)+3600,role})).toString('base64url')+'.x';
function ok(name,value=true){assert.ok(value,name);checks.push(name);console.log('PASS '+name)}
async function setup(options={}){
 const context=await browser.newContext({viewport:options.viewport||{width:1440,height:960},isMobile:!!options.mobile,hasTouch:!!options.mobile,...(options.storageState?{storageState:options.storageState}:{}),colorScheme:options.colorScheme||'dark',reducedMotion:options.reduced?'reduce':'no-preference'});const page=await context.newPage();
 if(options.preferences)await page.addInitScript(value=>{if(!localStorage.getItem('koomean_portal_prefs_v3'))localStorage.setItem('koomean_portal_prefs_v3',JSON.stringify(value))},options.preferences);
 if(options.rawPreferences)await page.addInitScript(value=>localStorage.setItem('koomean_portal_prefs_v3',value),options.rawPreferences);
 if(options.clock)await page.clock.install();
 if(options.blockAutoplay)await page.addInitScript(()=>{const play=HTMLMediaElement.prototype.play;let blocked=false;HTMLMediaElement.prototype.play=function(){if(!blocked){blocked=true;return Promise.reject(new DOMException('Autoplay disabled','NotAllowedError'))}return play.call(this)}});
 const calls=[],errors=[],consoleErrors=[],media=[];page.on('request',r=>{if(r.resourceType()==='media')media.push(r.url())});let signedRole='admin',rateLimited=false,requiresRegistration=false,registered=false,maintenance=false,gate=null,initialToolbarY=null;
 page.on('pageerror',e=>{errors.push(e.message);runtimeErrors.push(e.message)});page.on('console',e=>{if(e.type()==='error')consoleErrors.push(e.text())});
 if(options.storage)await page.addInitScript(()=>{localStorage.setItem('koomean_portal_session_v2',JSON.stringify({token:'legacy-private-token',user:{role:'admin',email:'old@example.invalid'}}))});
 if(options.blockStorage)await page.addInitScript(()=>{Storage.prototype.setItem=()=>{throw new DOMException('Unavailable')};Storage.prototype.getItem=()=>{throw new DOMException('Unavailable')};Storage.prototype.removeItem=()=>{throw new DOMException('Unavailable')}});
 await page.route('https://koomean.com/**',async r=>{const pathname=new URL(r.request().url()).pathname;const file=path.join(root,pathname==='/'?'index.html':pathname);if(!file.startsWith(root+'/')||!fs.existsSync(file))return r.fulfill({status:404,body:'missing'});return r.fulfill({path:file})});
 await page.route('https://accounts.google.com/gsi/client',async r=>{calls.push({action:'google'});if(options.googleDelay)await new Promise(resolve=>setTimeout(resolve,options.googleDelay));return r.fulfill({contentType:'application/javascript',body:`window.google={accounts:{id:{initialize:()=>{},renderButton:element=>{const b=document.createElement('button');b.textContent='Google fixture sign-in';element.appendChild(b)},disableAutoSelect:()=>{}}}}`})});
 await page.route('https://thesvg.org/**',r=>r.request().url().includes('registry')?r.fulfill({json:[{title:'GitHub',slug:'github'},{title:'Google',slug:'google'},{title:'Notion',slug:'notion'},{title:'OpenAI',slug:'openai'},{title:'Malicious',slug:'javascript:alert(1)'}]}):r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><circle cx="12" cy="12" r="10" fill="#888"/></svg>'}));
 await page.route('https://koomean-proxy.meanchannel52.workers.dev/**',async r=>{
  const params=new URLSearchParams(r.request().postData()),action=params.get('action');calls.push({action,authenticated:params.has('idToken'),params:Object.fromEntries([...params].filter(([key])=>key!=='idToken'))});
  if(action==='maintenanceStatus')return r.fulfill({json:{maintenance:{active:maintenance,note:'ทดสอบปิดปรับปรุง',reopenAt:Date.now()+60000}}});
  if(action==='bootstrap'){
   const authenticated=params.has('idToken');
   if(!authenticated && initialToolbarY===null)initialToolbarY=(await page.locator('.toolbar').boundingBox()).y;
   const data={applications:apps.filter(app=>authenticated||app.group==='public').concat(authenticated?[{rowIdx:99,name:'PrivateAdmin',url:'https://example.invalid/private',group:signedRole}]:[]),links,user:authenticated?{...user,role:signedRole}:{role:'public'},allUsers:authenticated&&signedRole==='admin'?[{...user,email:'x'.repeat(120)+'@example.invalid'}]:[]};
   if(authenticated&&requiresRegistration&&!registered)data.requireRegistration=true;
   if(gate&&authenticated){const current=gate;gate=null;current.started();await current.promise;}
   try{return await r.fulfill(rateLimited?{status:429,headers:{'Retry-After':'90'},json:{message:'Slow down'}}:{json:data})}catch{return}
  }
  if(action==='register'){registered=true;return r.fulfill({json:{success:true}})}
  if(action==='updateUserName')return r.fulfill({json:{success:true,name:params.get('newName')}});
  return r.fulfill({json:{success:true}});
 });
 await page.goto('https://koomean.com/',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>document.querySelector('#applications').getAttribute('aria-busy')==='false');
 return {page,context,calls,errors,consoleErrors,media,get initialToolbarY(){return initialToolbarY},setRole:role=>signedRole=role,setRate:v=>rateLimited=v,setRegistration:v=>requiresRegistration=v,setMaintenance:v=>maintenance=v,delayNext:()=>{let resolve,started;const promise=new Promise(r=>resolve=r);const ready=new Promise(r=>started=r);gate={promise,started};return{release:resolve,ready}},login:async(role='admin')=>{signedRole=role;await page.evaluate(token=>window.handleGoogleCredential({credential:token}),token(role));await page.waitForFunction(()=>document.querySelector('#applications').getAttribute('aria-busy')==='false');}};
}
async function within(page,selector){return page.locator(selector).evaluateAll(nodes=>nodes.filter(e=>e.offsetParent!==null).map(e=>{const r=e.getBoundingClientRect(),p=e.parentElement.getBoundingClientRect();return{selector:e.className||e.id,right:r.right,left:r.left,width:r.width,parentRight:p.right,parentLeft:p.left,scroll:e.scrollWidth,client:e.clientWidth}}).filter(r=>r.right>r.parentRight+2||r.left<r.parentLeft-2))}
async function close(page){await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('.modal-backdrop.open'))}
try{
 const env=await setup({storage:true});const {page,calls}=env;
 ok('Legacy token is removed without restoring unverified identity',await page.evaluate(()=>localStorage.getItem('koomean_portal_session_v2')===null)&&await page.locator('#admin-nav').isHidden());
 ok('Public link rail reserves layout space before the API responds',Math.abs((await page.locator('.toolbar').boundingBox()).y-env.initialToolbarY)<1);
 ok('Anonymous startup requests only bootstrap and maintenance',calls.filter(c=>!['bootstrap','maintenanceStatus'].includes(c.action)).length===0);
 ok('First render contains no blocking loader and has a high-priority poster',await page.locator('#page-loader').count()===0&&await page.locator('.hero-poster').getAttribute('fetchpriority')==='high');
 await page.waitForFunction(()=>!document.getElementById('hero-video').paused&&document.getElementById('hero-video').currentTime>0);
 ok('Muted local background autoplays and exposes its pause control',await page.locator('#hero-video').evaluate(e=>e.muted&&e.src.endsWith('/assets/hero-loop.mp4'))&&await page.locator('#video-toggle').getAttribute('aria-pressed')==='true');
 await page.locator('#video-toggle').click();await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'))});await page.waitForTimeout(100);
 ok('User pause survives visibility changes',await page.locator('#hero-video').evaluate(e=>e.paused)&&await page.locator('#video-toggle').getAttribute('aria-pressed')==='false');
 await page.locator('#video-toggle').click();await page.waitForFunction(()=>!document.getElementById('hero-video').paused);
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'))});ok('Hidden page pauses background video',await page.locator('#hero-video').evaluate(e=>e.paused));await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'))});await page.waitForFunction(()=>!document.getElementById('hero-video').paused);ok('Visible page resumes requested background playback');
 await page.setViewportSize({width:1440,height:360});await page.locator('.footer').scrollIntoViewIfNeeded();await page.waitForFunction(()=>document.querySelector('.modern-hero').getBoundingClientRect().bottom<=0);await page.waitForFunction(()=>document.getElementById('hero-video').paused);ok('Offscreen hero pauses video');await page.evaluate(()=>window.scrollTo(0,0));await page.waitForFunction(()=>!document.getElementById('hero-video').paused);await page.setViewportSize({width:1440,height:960});
 await page.locator('#marquee-toggle').click();ok('Link rail keeps an independent pause control',await page.locator('#marquee-section').evaluate(e=>e.classList.contains('user-paused'))&&await page.locator('#marquee-toggle').getAttribute('aria-pressed')==='true');await page.locator('#marquee-toggle').click();
 ok('Charcoal canvas and neutral surfaces keep blue as an accent',await page.evaluate(()=>getComputedStyle(document.body).backgroundColor==='rgb(20, 24, 29)'&&getComputedStyle(document.documentElement).getPropertyValue('--panel')==='#1b2027'));
 ok('Visible UI SVG icons resolve to local symbols',await page.locator('.ui-icon').evaluateAll(nodes=>nodes.filter(e=>e.getBoundingClientRect().width&&e.closest('[hidden]')===null).every(e=>{const use=e.querySelector('use');return use&&document.querySelector(use.getAttribute('href'))&&e.getBBox().width>0})));
 ok('Unsafe app and marquee URLs are filtered',await page.locator('a[href^="javascript:"],a[href*="password@"],a[href*="name:"]').count()===0);
 ok('Malicious names, descriptions and icon classes stay inert',await page.evaluate(()=>!window.__xss)&&await page.locator('#applications img[onerror],#applications [onclick]').count()===0);
 await page.locator('#app-search').fill('<img');await page.waitForFunction(()=>document.querySelectorAll('.app-card').length===1);ok('Search safely highlights raw HTML-like text',await page.locator('.app-name mark').textContent()==='<img'&&await page.locator('.app-name img').count()===0);await page.locator('[data-clear-search="app-search"]').click();await page.waitForFunction(()=>document.querySelectorAll('.app-card').length===4);ok('Search clear restores results and returns focus to the input',await page.locator('[data-clear-search="app-search"]').isHidden()&&await page.evaluate(()=>document.activeElement.id==='app-search'));
 await page.locator('[data-pin-url="https://example.invalid/Docs"]').click();ok('Favorites preserve case-sensitive URL identity and keyboard focus',await page.locator('[data-pin-url="https://example.invalid/Docs"]').getAttribute('aria-pressed')==='true'&&await page.locator('[data-pin-url="https://example.invalid/docs"]').getAttribute('aria-pressed')==='false'&&await page.evaluate(()=>document.activeElement?.dataset.pinUrl==='https://example.invalid/Docs'));
 await page.locator('#app-search').fill('no such app');await page.waitForFunction(()=>document.querySelectorAll('.app-card').length===0);ok('Empty search offers a readable state',await page.locator('.state-box').isVisible());await page.locator('#app-search').fill('');await page.waitForFunction(()=>document.querySelectorAll('.app-card').length===4);
 await page.locator('#settings-btn').click();await page.waitForTimeout(250);ok('Open dialog makes the page inert and traps keyboard focus',await page.locator('#main-content').evaluate(e=>e.inert)&&await page.locator('#settings-modal').evaluate(e=>e.contains(document.activeElement)));await page.keyboard.press('Shift+Tab');ok('Keyboard wraps inside the top dialog',await page.locator('#settings-modal').evaluate(e=>e.contains(document.activeElement)));await close(page);ok('Dialog close restores focus and hides content from accessibility tree',await page.evaluate(()=>document.activeElement.id==='settings-btn')&&await page.locator('#settings-modal').evaluate(e=>e.hidden&&e.inert&&e.getAttribute('aria-hidden')==='true'));
 await page.keyboard.press('Control+k');await page.locator('#command-search').fill('VeryLong');ok('Command palette long text stays inside its row',(await within(page,'.command-item>span:first-child')).length===0);await close(page);
 await env.login();ok('Only server verified admin response enables admin UI',await page.locator('#admin-nav').isVisible());ok('Token and account data are not persisted',await page.evaluate(()=>![...Object.values(localStorage)].some(s=>s.includes('fixture@example.invalid')||s.includes('exp'))));
 for(const width of [280,320,390,520,768,1024,1440]){
  await page.setViewportSize({width,height:900});
  for(const view of ['grid','list','compact']){
   await page.locator('#settings-btn').click();await page.locator(`#settings-modal [data-view="${view}"]`).click();await close(page);
   assert.deepEqual(await within(page,'.brand,.header-actions,.hero-title-modern,.hero-content-layer,.app-info,.app-name-row,.app-name'),[],`${width}/${view} content containment`);
   assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
   assert.ok(await page.evaluate(()=>{const r=id=>document.getElementById(id).getBoundingClientRect(),header=['command-btn','settings-btn','auth-btn'].map(id=>r(id).height);return Math.max(...header)-Math.min(...header)<.5&&Math.abs(r('refresh-btn').width-r('refresh-btn').height)<.5&&[...document.querySelectorAll('.view-btn,.refresh-btn,.icon-button')].filter(e=>e.offsetParent).every(e=>{const a=e.getBoundingClientRect(),b=e.querySelector('svg').getBoundingClientRect();return Math.abs(a.left+a.width/2-b.left-b.width/2)<.5&&Math.abs(a.top+a.height/2-b.top-b.height/2)<.5})}),`${width}/${view} control symmetry`);

  }
  checks.push(`Responsive ${width}px: grid, list, compact and long account/app text fit`);
 }
 await page.setViewportSize({width:768,height:900});await page.locator('#admin-nav').click();await page.waitForTimeout(250);ok('Tablet admin columns and fields fit',(await within(page,'.admin-layout,.field,.icon-picker-row')).length===0);await page.screenshot({path:out+'/admin-tablet-after.png',animations:'disabled'});await page.locator('#users-tab-btn').click();ok('Long user email fits admin row',(await within(page,'.admin-user-info,.admin-user-controls')).length===0);await close(page);
 await page.setViewportSize({width:320,height:640});await page.locator('#auth-btn').click();await page.waitForTimeout(250);ok('Account email wraps fully within mobile dialog',(await within(page,'.user-detail-copy,#account-email,.inline-form,.field')).length===0);await page.screenshot({path:out+'/account-mobile-after.png',animations:'disabled'});await close(page);
 await page.locator('#admin-nav').click();await page.locator('[data-admin-action="edit"]').first().click();await page.locator('#admin-url').fill('javascript:alert(1)');const writesBefore=calls.length;await page.locator('#admin-submit-btn').click();ok('Admin invalid URL validation prevents writes',calls.length===writesBefore&&await page.locator('#toast-message').textContent()!=='');await page.locator('#choose-logo-btn').click();await page.waitForSelector('.logo-result');ok('Nested logo picker isolates focus and filters invalid SVG slugs',await page.locator('#admin-modal').evaluate(e=>e.inert)&&await page.locator('.logo-result img[src=""]').count()===0&&await page.locator('[data-logo^="javascript:"]').count()===0);ok('Logo search and tile previews stay centered and square',await page.evaluate(()=>{const input=document.getElementById('logo-search').getBoundingClientRect(),icon=document.querySelector('#logo-modal .search-symbol').getBoundingClientRect();return Math.abs(input.top+input.height/2-icon.top-icon.height/2)<.5&&[...document.querySelectorAll('.logo-preview')].every(e=>{const a=e.getBoundingClientRect(),b=e.parentElement.getBoundingClientRect();return Math.abs(a.width-a.height)<.5&&Math.abs(a.left+a.width/2-b.left-b.width/2)<.5})}));await page.keyboard.press('Escape');ok('Closing nested dialog restores the parent dialog',await page.locator('#admin-modal').evaluate(e=>!e.inert&&!e.hidden));await close(page);
 await page.locator('#admin-nav').click();await page.locator('#users-tab-btn').click();env.setRole('public');await page.locator('[data-save-user]').first().click();await page.waitForFunction(()=>document.querySelector('#admin-modal').hidden);ok('Losing admin role closes management UI and clears private admin DOM',await page.locator('#admin-users').textContent()===''&&await page.locator('#admin-nav').isHidden());await env.login();
 await page.setViewportSize({width:1440,height:960});await page.locator('#settings-btn').click();await page.locator('[data-theme-value="light"]').click();await close(page);await page.waitForTimeout(250);ok('Theme preference and selected control stay synchronized',await page.evaluate(()=>document.documentElement.dataset.theme==='light')&&await page.locator('[data-theme-value="light"]').getAttribute('aria-pressed')==='true');
 const delayed=env.delayNext();await page.locator('#refresh-btn').click();await delayed.ready;await page.locator('#auth-btn').click();await page.locator('#logout-btn').click();await page.waitForFunction(()=>document.querySelector('#applications').getAttribute('aria-busy')==='false');delayed.release();await page.waitForTimeout(150);ok('Late authenticated response cannot restore data after logout',await page.locator('#admin-nav').isHidden()&&await page.locator('#applications').getAttribute('aria-busy')==='false'&&!await page.locator('#applications').textContent().then(t=>t.includes('PrivateAdmin')));
 const countBefore=await page.locator('.app-card').count();env.setRate(true);await page.locator('#refresh-btn').click();await page.waitForFunction(()=>!document.querySelector('#refresh-btn').disabled);const rateCalls=calls.length;await page.locator('#refresh-btn').click();ok('429 preserves visible apps and honors Retry-After',await page.locator('.app-card').count()===countBefore&&calls.length===rateCalls);
 ok('No application runtime error during interactions',env.errors.length===0);
 await env.context.close();
 const prefs=await setup(),pp=prefs.page;await pp.mouse.move(0,0);
 const railTime=await pp.locator('.marquee-track').evaluate(e=>e.getAnimations()[0].currentTime);await pp.waitForFunction(time=>document.querySelector('.marquee-track').getAnimations()[0].currentTime>time+100,railTime);
 ok('Social links start moving without interaction at the faster default speed',await pp.locator('.marquee-track').evaluate(e=>getComputedStyle(e).animationDuration==='38s'&&getComputedStyle(e).animationPlayState==='running'));
 ok('Changing scroll speed preserves the current link position',await pp.evaluate(()=>{const rail=document.querySelector('.marquee-track');rail.getAnimations()[0].currentTime=21000;const before=new DOMMatrix(getComputedStyle(rail).transform).m41;const select=document.getElementById('marquee-speed');select.value='fast';select.dispatchEvent(new Event('change',{bubbles:true}));const after=new DOMMatrix(getComputedStyle(rail).transform).m41;return Math.abs(after-before)<.5&&getComputedStyle(rail).animationDuration==='28s'}));
 await pp.locator('#marquee-toggle').click();await pp.locator('#marquee-toggle').click();await pp.mouse.move(0,0);
 ok('Play resumes the rail while its control retains focus',await pp.evaluate(()=>document.activeElement.id==='marquee-toggle'&&getComputedStyle(document.querySelector('.marquee-track')).animationPlayState==='running'));
 await pp.locator('#marquee-section').hover();ok('Pointer hover temporarily pauses the rail',await pp.locator('.marquee-track').evaluate(e=>getComputedStyle(e).animationPlayState==='paused'));await pp.mouse.move(0,0);
 await pp.locator('#marquee-toggle').focus();await pp.keyboard.press('Shift+Tab');ok('Keyboard focus on a social link pauses it for activation',await pp.evaluate(()=>document.activeElement.classList.contains('marquee-card')&&getComputedStyle(document.querySelector('.marquee-track')).animationPlayState==='paused'));await pp.keyboard.press('Tab');await pp.mouse.move(0,0);
 ok('Temporary focus pause does not overwrite the saved autoplay choice',await pp.evaluate(()=>JSON.parse(localStorage.getItem('koomean_portal_prefs_v3')).marqueeEnabled===true&&getComputedStyle(document.querySelector('.marquee-track')).animationPlayState==='running'));
 await pp.locator('#favorites-filter').click();ok('An empty favorites filter explains how to add stars',await pp.locator('.app-card').count()===0&&await pp.locator('#show-all-apps').isVisible());await pp.locator('#show-all-apps').click();
 await pp.locator('[data-pin-url="https://example.invalid/Docs"]').click();await pp.locator('#favorites-filter').click();ok('Favorites filter and count use the actual starred URL',await pp.locator('.app-card').count()===1&&await pp.locator('#favorites-count').textContent()==='1'&&await pp.locator('.app-card-body').getAttribute('href')==='https://example.invalid/Docs');
 await pp.locator('#app-search').fill('Case B');await pp.waitForSelector('#show-all-apps');ok('Favorites and search combine without including unstarred apps',await pp.locator('.app-card').count()===0);await pp.locator('#show-all-apps').click();ok('Show all clears restrictive search and favorites filters',await pp.locator('.app-card').count()===4&&await pp.locator('#app-search').inputValue()===''&&await pp.locator('#favorites-filter').getAttribute('aria-pressed')==='false');await pp.locator('#favorites-filter').click();
 await pp.locator('#settings-btn').click();await pp.locator('[data-theme-value="light"]').click();await pp.locator('#settings-modal [data-view="list"]').click();await pp.locator('[data-language-value="en"]').click();await pp.locator('#marquee-speed').selectOption('fast');await pp.locator('#marquee-enabled').uncheck();await pp.locator('#video-enabled').uncheck();await pp.locator('#data-saver').check();await close(pp);
 await pp.reload();await pp.waitForFunction(()=>document.querySelector('#applications').getAttribute('aria-busy')==='false');await pp.waitForTimeout(1400);
 ok('Reload restores theme, language, layout, motion, data saver and favorite filter',await pp.evaluate(()=>{const p=JSON.parse(localStorage.getItem('koomean_portal_prefs_v3'));return p.theme==='light'&&p.lang==='en'&&p.view==='list'&&!p.marqueeEnabled&&p.marqueeSpeed==='fast'&&!p.videoEnabled&&p.dataSaver&&p.favoritesOnly&&document.documentElement.dataset.theme==='light'&&document.documentElement.lang==='en'&&document.documentElement.dataset.view==='list'&&!document.getElementById('marquee-enabled').checked&&!document.getElementById('video-enabled').checked&&document.getElementById('data-saver').checked&&document.getElementById('marquee-speed').value==='fast'&&document.querySelectorAll('.app-card').length===1}));
 ok('Restored video-off preference leaves no media source',await pp.locator('#hero-video').getAttribute('src')===null&&await pp.locator('#video-toggle').isDisabled());
 const reopened=await setup({storageState:await prefs.context.storageState()});await reopened.page.waitForTimeout(1400);ok('A fresh browser context restores the saved choices without any clicks',await reopened.page.locator('#favorites-filter').getAttribute('aria-pressed')==='true'&&await reopened.page.locator('#data-saver').isChecked()&&await reopened.page.locator('.marquee-track').evaluate(e=>getComputedStyle(e).animationDuration==='28s'&&getComputedStyle(e).animationPlayState==='paused')&&reopened.media.length===0);
 await reopened.login();await reopened.page.locator('#settings-btn').click();await reopened.page.locator('#reset-preferences').click();await close(reopened.page);await reopened.page.waitForFunction(()=>!document.getElementById('hero-video').paused);
 ok('Reset restores defaults while retaining stars and signed-in identity',await reopened.page.evaluate(()=>document.documentElement.dataset.theme==='dark'&&document.documentElement.lang==='th'&&document.documentElement.dataset.view==='grid'&&document.getElementById('marquee-enabled').checked&&document.getElementById('video-enabled').checked&&!document.getElementById('data-saver').checked&&document.getElementById('marquee-speed').value==='normal'&&document.getElementById('favorites-filter').getAttribute('aria-pressed')==='false')&&await reopened.page.locator('[data-pin-url="https://example.invalid/Docs"]').getAttribute('aria-pressed')==='true'&&await reopened.page.locator('#admin-nav').isVisible());
 await reopened.page.reload();await reopened.page.waitForFunction(()=>document.querySelector('#applications').getAttribute('aria-busy')==='false');ok('Reset defaults are saved for the next visit',await reopened.page.locator('#marquee-speed').inputValue()==='normal'&&!await reopened.page.locator('#data-saver').isChecked()&&await reopened.page.locator('#favorites-filter').getAttribute('aria-pressed')==='false');await reopened.context.close();await prefs.context.close();
 const paused=await setup();await paused.page.waitForFunction(()=>!document.getElementById('hero-video').paused);await paused.page.locator('#video-toggle').click();await paused.page.locator('#marquee-toggle').click();const pauseMedia=paused.media.length;await paused.page.reload();await paused.page.waitForFunction(()=>document.querySelector('#applications').getAttribute('aria-busy')==='false');await paused.page.waitForTimeout(1400);
 ok('Direct pause buttons persist independently across reload without fetching video',await paused.page.locator('#hero-video').getAttribute('src')===null&&paused.media.length===pauseMedia&&!await paused.page.locator('#video-enabled').isChecked()&&!await paused.page.locator('#marquee-enabled').isChecked());await paused.context.close();
 const saver=await setup({preferences:{dataSaver:true}});await saver.page.waitForTimeout(1400);ok('Data saver blocks startup media while retaining the video preference',saver.media.length===0&&await saver.page.locator('#hero-video').getAttribute('src')===null&&await saver.page.locator('#video-enabled').isChecked());
 await saver.page.locator('#settings-btn').click();await saver.page.locator('#data-saver').uncheck();await close(saver.page);await saver.page.waitForFunction(()=>document.getElementById('hero-video').currentTime>0);ok('Leaving data saver restores the requested video playback');
 await saver.page.locator('#settings-btn').click();await saver.page.locator('#data-saver').check();ok('Turning on data saver detaches an already-playing video',await saver.page.locator('#hero-video').evaluate(e=>e.paused&&e.hidden&&!e.hasAttribute('src'))&&await saver.page.locator('#video-toggle').isDisabled());await close(saver.page);const saverMedia=saver.media.length;await saver.page.reload();await saver.page.waitForTimeout(1400);ok('Data saver survives reload without another media download',saver.media.length===saverMedia&&await saver.page.locator('#hero-video').getAttribute('src')===null);await saver.context.close();
 const touch=await setup({mobile:true,viewport:{width:390,height:844}});await touch.page.locator('#marquee-toggle').tap();await touch.page.locator('#marquee-toggle').tap();ok('Touch play is not held by a sticky hover or button focus',await touch.page.locator('.marquee-track').evaluate(e=>getComputedStyle(e).animationPlayState==='running'));await touch.context.close();
 const migrated=await setup({preferences:{theme:'light',lang:'en',view:'compact'}});ok('Older saved preferences retain existing choices and adopt new defaults',await migrated.page.evaluate(()=>document.documentElement.dataset.theme==='light'&&document.documentElement.lang==='en'&&document.documentElement.dataset.view==='compact'&&document.getElementById('marquee-enabled').checked&&document.getElementById('video-enabled').checked&&!document.getElementById('data-saver').checked&&document.getElementById('marquee-speed').value==='normal'));await migrated.context.close();
 const invalidPrefs=await setup({preferences:{marqueeEnabled:'false',videoEnabled:0,dataSaver:'true',favoritesOnly:[],marqueeSpeed:['fast']}});ok('Invalid preference types fall back to safe defaults',await invalidPrefs.page.evaluate(()=>document.getElementById('marquee-enabled').checked&&document.getElementById('video-enabled').checked&&!document.getElementById('data-saver').checked&&document.getElementById('marquee-speed').value==='normal'&&document.getElementById('favorites-filter').getAttribute('aria-pressed')==='false'));await invalidPrefs.context.close();
 const corruptPrefs=await setup({rawPreferences:'{broken JSON'});ok('Corrupt stored preferences do not stop the catalog or controls',await corruptPrefs.page.locator('.app-card').count()===4&&await corruptPrefs.page.locator('#marquee-speed').inputValue()==='normal'&&corruptPrefs.errors.length===0);await corruptPrefs.context.close();
 const registered=await setup();registered.setRegistration(true);await registered.page.evaluate(t=>handleGoogleCredential({credential:t}),token('public'));await registered.page.waitForSelector('#register-modal.open');ok('New users see registration with consent required',await registered.page.locator('#register-btn').isDisabled());await registered.page.locator('#register-terms-accepted').check();await registered.page.locator('#register-btn').click();await registered.page.waitForSelector('#register-modal',{state:'hidden'});await registered.page.waitForFunction(()=>document.querySelector('#applications').getAttribute('aria-busy')==='false');ok('Registration refreshes account and catalog automatically',await registered.page.locator('#auth-label').textContent()==='บัญชี');await registered.context.close();
 const ordinary=await setup();await ordinary.login('notadmin');ok('Substring admin role does not grant admin controls',await ordinary.page.locator('#admin-nav').isHidden());await ordinary.context.close();
 const gis=await setup();await gis.page.locator('#auth-btn').click();await gis.page.waitForSelector('#google-button button');await gis.page.keyboard.press('Escape');ok('Closing login tears down the provider frame before hiding the modal',await gis.page.locator('#google-button').evaluate(e=>e.childElementCount===0));await gis.context.close();
 const slow=await setup({googleDelay:500});await slow.page.locator('#auth-btn').click();await slow.page.waitForSelector('#login-modal.open');await slow.page.keyboard.press('Escape');await slow.page.waitForTimeout(650);ok('Closing login while Google loads does not reopen it',await slow.page.locator('#login-modal').isHidden());await slow.context.close();
 const reduced=await setup({reduced:true});await reduced.page.waitForTimeout(1400);ok('Reduced motion stops marquee, hero entrance and automatic video fetch',await reduced.page.locator('.marquee-track').evaluate(e=>getComputedStyle(e).animationName==='none')&&await reduced.page.locator('#hero-title').evaluate(e=>getComputedStyle(e).opacity==='1')&&await reduced.page.locator('#hero-video').getAttribute('src')===null&&await reduced.page.locator('#video-toggle').getAttribute('aria-pressed')==='false');await reduced.context.close();
 const denied=await setup({blockAutoplay:true});await denied.page.waitForTimeout(1500);ok('Denied autoplay preserves poster and offers manual playback without a toast',await denied.page.locator('#hero-video').evaluate(e=>e.paused&&e.hidden)&&await denied.page.locator('#video-toggle').getAttribute('aria-pressed')==='false'&&!await denied.page.locator('#toast').evaluate(e=>e.classList.contains('show')));await denied.page.locator('#video-toggle').click();await denied.page.waitForFunction(()=>!document.getElementById('hero-video').paused);ok('Manual playback works after denied autoplay');await denied.context.close();
 const lightSystem=await setup({colorScheme:'light'});ok('New visits start with charcoal even on a light system',await lightSystem.page.evaluate(()=>document.documentElement.dataset.theme==='dark'&&getComputedStyle(document.body).backgroundColor==='rgb(20, 24, 29)'));await lightSystem.context.close();
 const unavailable=await setup({blockStorage:true});await unavailable.page.locator('#settings-btn').click();await unavailable.page.locator('[data-theme-value="light"]').click();await unavailable.page.locator('[data-language-value="en"]').click();await unavailable.page.locator('#data-saver').check();ok('Blocked saving is clearly reported even after a language change',await unavailable.page.locator('#preferences-status').textContent().then(t=>t.includes('blocked saving')));await close(unavailable.page);await unavailable.page.locator('[data-pin-url]').first().click();ok('Blocked storage does not break theme or favorites',unavailable.errors.length===0);await unavailable.context.close();
 const csp=await setup();await csp.page.evaluate(()=>{const script=document.createElement('script');script.textContent='window.__injected=1';document.body.appendChild(script);const image=document.createElement('img');image.setAttribute('onerror','window.__inlineHandler=1');image.src='data:image/png,bad';document.body.appendChild(image)});await csp.page.waitForTimeout(100);ok('Browser CSP blocks injected inline script and event handler',await csp.page.evaluate(()=>!window.__injected&&!window.__inlineHandler));await csp.context.close();
 const polling=await setup({clock:true});let start=polling.calls.filter(c=>c.action==='maintenanceStatus').length;await polling.page.clock.runFor(15000);ok('Maintenance no longer polls every 15 seconds',polling.calls.filter(c=>c.action==='maintenanceStatus').length===start);await polling.page.clock.runFor(46000);await polling.page.waitForTimeout(1);ok('Maintenance refreshes on the 60 second cadence',polling.calls.filter(c=>c.action==='maintenanceStatus').length===start+1);
 await polling.page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'))});await polling.page.clock.runFor(120000);ok('Hidden tabs stop maintenance network polling',polling.calls.filter(c=>c.action==='maintenanceStatus').length===start+1);
 polling.setMaintenance(true);await polling.page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'))});await polling.page.waitForSelector('#global-maintenance-overlay:not([hidden])');ok('Maintenance overlay uses safe text and isolates page focus',await polling.page.locator('#main-content').evaluate(e=>e.inert)&&await polling.page.locator('#global-maintenance-note').textContent()==='ทดสอบปิดปรับปรุง');await polling.page.evaluate(()=>document.getElementById('settings-btn').click());ok('Maintenance blocks delayed dialog opening',await polling.page.locator('.modal-backdrop.open').count()===0&&await polling.page.locator('#global-maintenance-overlay').evaluate(e=>e===document.activeElement));const maintenanceBootstraps=polling.calls.filter(c=>c.action==='bootstrap').length;await polling.page.clock.runFor(11000);await polling.page.evaluate(()=>{document.getElementById('connection-status').classList.add('offline');window.dispatchEvent(new Event('online'))});await polling.page.waitForTimeout(50);ok('Maintenance blocks catalog retries and reconnect requests',polling.calls.filter(c=>c.action==='bootstrap').length===maintenanceBootstraps);await polling.context.close();
 ok('No application runtime error in any test browser context',runtimeErrors.length===0);
 fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({passed:checks.length,checks},null,2)+'\n');console.log(`${checks.length} browser checks passed`);
}finally{clearTimeout(watchdog);await browser.close()}
