import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {transform} from 'esbuild';
const hash = value => createHash('sha256').update(value).digest('hex').slice(0,16);
let html = fs.readFileSync('src/index.html','utf8').replace('/* BUILD_MAINTENANCE */',fs.readFileSync('src/maintenance.js','utf8'));
const scripts = [], styles = [fs.readFileSync('src/vendor.css','utf8')];
html = html.replace(/<style>([\s\S]*?)<\/style>/g, (_,css) => { styles.push(css); return ''; });
styles.push(fs.readFileSync('src/enhancements.css','utf8'));
html = html.replace(/<script>([\s\S]*?)<\/script>/g, (_,js) => { scripts.push(js); return ''; });
html = html.replace(/<link[^>]+href="https:\/\/(?:fonts.googleapis.com|fonts.gstatic.com|cdnjs.cloudflare.com)[^"]+"[^>]*>/g,'');
html = html.replace(/<!--[\s\S]*?-->/g,'');
const css = (await transform(styles.join('\n'),{loader:'css',minify:true,target:'es2022'})).code;
const js = (await transform(scripts.join('\n;\n'),{loader:'js',minify:true,target:'es2022',legalComments:'none'})).code;
fs.mkdirSync('assets',{recursive:true});
for (const file of fs.readdirSync('assets')) if (/^(app|portal)-[a-f0-9]+\.(js|css)$/.test(file)) fs.unlinkSync('assets/'+file);
const cssFile = 'portal-'+hash(css)+'.css', jsFile = 'app-'+hash(js)+'.js';
fs.writeFileSync('assets/'+cssFile,css); fs.writeFileSync('assets/'+jsFile,js);
const csp = "default-src 'self'; base-uri 'none'; object-src 'none'; script-src 'self' https://accounts.google.com/gsi/; script-src-attr 'none'; style-src 'self' 'unsafe-inline' https://accounts.google.com/gsi/style; font-src 'self'; img-src 'self' https: data:; media-src 'self' https://d8j0ntlcm91z4.cloudfront.net; connect-src 'self' https://koomean-proxy.meanchannel52.workers.dev https://accounts.google.com/gsi/ https://thesvg.org/api/registry.json; frame-src https://accounts.google.com/gsi/; form-action 'none'; upgrade-insecure-requests";
html = html.replace('<meta charset="utf-8">','<meta charset="utf-8">\n<meta http-equiv="Content-Security-Policy" content="'+csp+'">');
html = html.replace('</head>',`<link rel="stylesheet" href="assets/${cssFile}">\n<link rel="preload" as="font" type="font/woff2" crossorigin href="assets/ibm-2e57acf1ca9e.woff2">\n<link rel="preload" as="image" href="assets/hero-poster.webp" fetchpriority="high">\n<script src="assets/${jsFile}" defer></script>\n</head>`);
html = html.replace(/\n\s*\n/g,'\n'); fs.writeFileSync('index.html',html);
const manifest = {htmlBytes:Buffer.byteLength(html),css:{file:cssFile,bytes:Buffer.byteLength(css)},js:{file:jsFile,bytes:Buffer.byteLength(js)}};
fs.writeFileSync('build-manifest.json',JSON.stringify(manifest,null,2)+'\n'); console.log(manifest);
